acr_name                                 = "testACRnewRegisTrytestingdctiac"
azure_resource_group                      = "acrTest"
location                                 = "Central US"
acr_sku                                  = "Premium"
aks_name = "rg-aks"
aks_resource_group = "ems-aks-rg"
